version: '2'
services:
  nomad-client:
    image: jsecchiero/nomad-client
    network_mode: "host"
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"
      - "4646:4646/udp"
      - "4647:4647/udp"
      - "4648:4648/udp"
    volumes:
      - nomad-client-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nomad-client-data:
